site_name: Net
site_author: drake
site_description: Net document
copyright: Copyright &copy; 2018 - 2020 Drake

repo_name: GitHub
repo_url: https://github.com/liangjingkanji/Net

extra_css:
  - css/extra.css

docs_dir: docs

theme:
  name: material
  custom_dir: docs/material

  palette:
    scheme: drake
    primary: white

  font: false

  language: zh

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed

nav:
  - 使用: index.md
  - 协程请求: parallel.md
  - 同步请求: sync-request.md
  - 队列请求: enqueue-request.md
  - ViewModel: view-model.md
  - 请求参数: request-params.md
  - 创建作用域: scope.md
  - 全局配置: config.md
  - OkHttpClient: okhttp-client.md
  - 全局错误处理: error-handle.md
  - 拦截器: interceptor.md
  - Https证书: https.md
  - 自定义转换器:
      - 创建转换器: converter.md
      - 任何泛型: kotlin-serialization.md
      - 转换Data字段: convert-data-field.md
      - 转换JSON数组: convert-json-array.md
  - 异常追踪: exception-track.md
  - 自动化:
      - 自动加载框: auto-dialog.md
      - 自动缺省页: auto-state.md
      - 自动下拉刷新: auto-refresh.md
      - 自动分页加载: auto-page.md
  - 切换线程: switch-dispatcher.md
  - 标签: tag.md
  - 上传文件: upload-file.md
  - 下载文件: download-file.md
  - 进度监听: progress.md
  - 嵌套作用域: nested-scope.md
  - 最快请求结果: fastest.md
  - 重复请求: unique.md
  - 节流阀: debounce.md
  - 取消请求: cancel.md
  - 日志拦截器: log-recorder.md
  - 轮循器: interval.md
  - 更新日志: updates.md
  - 3.x文档: api/index.html
